### ISSUE TITLE
Use wcwidth to compute len of printable string

### ISSUE THREAD

**Issue by Eldalie** [AharonSambol/PrettyPrintTree#10]
Hello,

When we combine PrettyPrintTree with other package like [climage](https://pypi.org/project/climage/) the len is miscalculate and the tree is Broken.
Do you thinks that it possible to use wcswidth ?

Thanks for this package ?

**Comment by AharonSambol** [comment]
Yup, I just pushed a new version which should work now.
(Although the whole thing is a mess and I'd like to do a complete rewrite soon)

**Comment by Eldalie** [comment]
Thanks you very much !
