### ISSUE TITLE
[versioning] Consider using semantic versionin

### ISSUE THREAD

**Issue by ADraginda** [AharonSambol/PrettyPrintTree#3]
https://github.com/AharonSambol/PrettyPrintTree/blob/master/setup.py#L9

Would be able to provide better-implied meaning if it was instead suffixed with `.0`

Just in case you haven't run into this before, here's the [semantic versioning](https://semver.org/) documentation.

With a quick summary in the first paragraph:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards compatible manner, and
> PATCH version when you make backwards compatible bug fixes.

**Comment by AharonSambol** [comment]
I just didn't want to change anything about the version until I actually changed it. But no worries I'm about to do just that.

**Comment by AharonSambol** [comment]
Just realized I probably just versioned this wrong 😅
