### ISSUE TITLE
No indication of required Python version

### ISSUE THREAD

**Issue by haxsaw** [AharonSambol/PrettyPrintTree#4]
I wanted to try this on a work project where 3.7 is the conventional version, however importing PretyPrintTree failed in PrintTree.py on line 152 complaining about ':='. I think this is only supported in 3.8 and beyond, so it would be nice if at least the doc mentioned this, and better yet the proper version is named in the the setup so it would have failed to install on 3.7. Best would be to still support 3.7 and not use the walrus operator, but your call regarding which versions you wish to support.

**Comment by AharonSambol** [comment]
I removed the walrus operators so I'm pretty sure it will now work on 3.7 (and added it to the readme too)
