### ISSUE TITLE
Print Binary Trees properly

### ISSUE THREAD

**Issue by pota2dev** [AharonSambol/PrettyPrintTree#9]
For Binary Trees, code shown in README `lambda node: [node.child_left, node.child_right]` doesn't work if `[node.child_left, node.child_right]` contains `None`

A workaround for this is to use:
```Python
pt = PrettyPrintTree(lambda x: [x for x in [x.left, x.right] if x!= None], lambda x: x.elem)
pt(root)
```
But it doesn't preserve the position of left child / right child. So when a node has a single child it gets printed parallelly.

![image](https://github.com/AharonSambol/PrettyPrintTree/assets/36124755/2132af53-20d2-46d2-b559-3b3c84438101)

**Comment by AharonSambol** [comment]
Oops... That's a pretty dumb mistake. Thanks for pointing it out! I fixed the example now

**Comment by pota2dev** [comment]
@AharonSambol Thanks for the fast response. Isn't there any way to skip printing the box of an `item` of the `list` if it's `None`?
